name: default_task

shape_meta: &shape_meta
  obs:
    environment_point_cloud:
      shape: [2048, 6]
      type: point_cloud
    garment_point_cloud:
      shape: [2048, 3]
      type: point_cloud
    points_affordance_feature:
      shape: [2048, 4]
      type/: point_cloud
    agent_pos:
      shape: [60]
      type: low_dim
  action:
    shape: [60]

env_runner:
  _target_: structure_aware_diffusion_policy_garment.env_runner.robot_runner.RobotRunner
  max_steps: 300
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  task_name: robot

dataset:
  _target_: structure_aware_diffusion_policy_garment.dataset.robot_dataset.RobotDataset
  zarr_path: data/default_task.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 0
  val_ratio: 0.02
  max_train_episodes: null
